name: SP Release
on:
  workflow_dispatch:

jobs:
  sprelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get Versions
        id: versions
        run: |
          OLDVER=$(sed -n "s/.*\([0-9]\.[0-9]\.[0-9]*\).*/\1/p" "$GITHUB_WORKSPACE/skyrim-platform/package.json" | head -1)
          MINOR=$(echo "$OLDVER" | sed -n "s/[0-9]\.\([0-9]\)\.[0-9]/\1/p")
          NEWMINOR=$((MINOR+1))
          NEWVER=$(echo "$OLDVER" | sed -n "s/\.$MINOR\./\.$NEWMINOR\./p")
          SHORTVER=$(echo "$NEWVER" | sed -r "s/\.0//g")
          echo "OLDVER=$OLDVER" >> $GITHUB_ENV
          echo "NEWVER=$NEWVER" >> $GITHUB_ENV
          echo "SHORTVER=$SHORTVER" >> $GITHUB_ENV
          echo "oldver=$OLDVER" >> $GITHUB_OUTPUT
          echo "newver=$NEWVER" >> $GITHUB_OUTPUT
          echo "shortver=$SHORTVER" >> $GITHUB_OUTPUT
          echo "Detect oldver: $OLDVER"
          echo "Newver: $NEWVER"

      - name: Replace Version In Files
        run: |
          chmod 777 "$GITHUB_WORKSPACE/skyrim-platform/src/platform_se/CMakeLists.txt"
          chmod 777 "$GITHUB_WORKSPACE/skyrim-platform/src/platform_se/skyrim_platform/DevApi.cpp"
          chmod 777 "$GITHUB_WORKSPACE/skyrim-platform/package.json"
          chmod 777 "$GITHUB_WORKSPACE/skyrim-platform/tools/plugin-example/package.json"
          chmod 777 "$GITHUB_WORKSPACE/skymp5-client/src/version.ts"
          sed -i "s/$OLDVER/$NEWVER/g" "$GITHUB_WORKSPACE/skyrim-platform/src/platform_se/CMakeLists.txt"
          sed -i "s/$OLDVER/$NEWVER/g" "$GITHUB_WORKSPACE/skyrim-platform/src/platform_se/skyrim_platform/DevApi.cpp"
          sed -i "s/$OLDVER/$NEWVER/g" "$GITHUB_WORKSPACE/skyrim-platform/package.json"
          sed -i "s/$OLDVER/$NEWVER/g" "$GITHUB_WORKSPACE/skyrim-platform/tools/plugin-example/package.json"
          sed -i "s/$OLDVER/$NEWVER/g" "$GITHUB_WORKSPACE/skymp5-client/src/version.ts"
          chmod 644 "$GITHUB_WORKSPACE/skyrim-platform/src/platform_se/CMakeLists.txt"
          chmod 644 "$GITHUB_WORKSPACE/skyrim-platform/src/platform_se/skyrim_platform/DevApi.cpp"
          chmod 644 "$GITHUB_WORKSPACE/skyrim-platform/package.json"
          chmod 644 "$GITHUB_WORKSPACE/skyrim-platform/tools/plugin-example/package.json"
          chmod 644 "$GITHUB_WORKSPACE/skymp5-client/src/version.ts"

      - name: Generate Changelog
        run: |
          chmod 777 "$GITHUB_WORKSPACE/docs/release"
          TARGET="$GITHUB_WORKSPACE/docs/release/sp-$SHORTVER.md"
          cp "$GITHUB_WORKSPACE/docs/release/changelog_template.md" "$TARGET"
          sed -i "s/{{NEWVER}}/$NEWVER/g" "$TARGET"
          sed -i "s/{{OLDVER}}/$OLDVER/g" "$TARGET"

          for file in `find "$GITHUB_WORKSPACE/docs/release/dev" -type f -name "sp*.md"`
          do
            content=$(< $file)
            if grep -q "^#" "$file"; then
              echo "$content" >> "$TARGET"
              echo $'\n' >> "$TARGET"
            else
              echo "- $content" >> ./temp.txt
              echo $'\n' >> ./temp.txt
            fi
          done

          if [ -e temp.txt ]; then
            echo "## Other changes"$'\n' >> "$TARGET"
            content=$(< ./temp.txt)
            echo "$content" >> "$TARGET"
            echo $'\n' >> "$TARGET"
            rm -f ./temp.txt
          fi

      - name: Remove files used in changelog
        run: |
          for file in `find "$GITHUB_WORKSPACE/docs/release/dev" -type f -name "sp*.md"`
          do
            rm $file
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "release(skyrim-platform): version ${{ steps.versions.outputs.shortver }}"
          title: "release(skyrim-platform): version ${{ steps.versions.outputs.shortver }}"
          body: Bot put here this release PR, enjoy...
          branch: "release-sp${{ steps.versions.outputs.shortver }}"
